In [1]:
from py3_mytranspose.mytranspose import *

In [2]:
import pandas as pd
import numpy as np

In [3]:
def compare(x,y):
    try:
        same = (np.isnan(x) & np.isnan(y)) | (x == y)
    except:
        same = (x==y)
    all_same = np.alltrue(same)
    return all_same

In [4]:
# testing unit
def test_mytranspose(x):
    mytp = mytranspose(x)
    tp = np.transpose(x)
    success = compare(mytp, tp)
    if success:
        print("mytraspose successfully transpose ")
        print(x)
        print("into")
        print(mytp)
        print()
    else:
        print("falied to transpose")
        print(x)
        print(tp)
        print("should have been obtained. but")
        print(mytp)
        print("was obtained")
        print("")
    return success


In [5]:
# dataset null
null_1 = None # null scalar
null_2 = [] # empty list
null_3 = np.array([]) # empty array

In [6]:
# testing null case
print("testing if null is converted successfully")
successed_all = True
for x in [null_1,null_2,null_3]:
    successed = test_mytranspose(x)
    successed_all = successed_all & successed
if successed_all:
    print("function mytranspose can transpose null")


testing if null is converted successfully
mytraspose successfully transpose 
None
into
None

mytraspose successfully transpose 
[]
into
[]

mytraspose successfully transpose 
[]
into
[]

function mytranspose can transpose null


In [7]:
# dataset 0d
scalar_numeric = 1234
scalar_string = "string"
scalar_nan = np.nan
scalar_inf = np.inf

In [8]:
# testing 0d
# testing scalar case
print("testing if scalar is converted successfully")
successed_all = True
for x in [scalar_numeric, scalar_string, scalar_nan, scalar_inf]:
    successed = test_mytranspose(x)
    successed_all = successed_all & successed
if successed_all:
    print("function mytranspose can transpose scalar")

testing if scalar is converted successfully
mytraspose successfully transpose 
1234
into
1234

mytraspose successfully transpose 
string
into
string

mytraspose successfully transpose 
nan
into
nan

mytraspose successfully transpose 
inf
into
inf

function mytranspose can transpose scalar


In [9]:
#dataset vector
vector_1 = [1,2,3,4] # list of number
vector_2 = ["this", "is", "a", "apple"] #list of str
vector_3 = np.array([1,2,3,4]) # array of number
vector_4 = [True, True, False, False]

In [10]:
# testing 1d
# testing vector case
print("testing if vector is converted successfully")
successed_all = True
for x in [vector_1, vector_2, vector_3, vector_4]:
    successed = test_mytranspose(x)
successed_all = successed_all & successed
if successed_all:
    print("function mytranspose can transpose vector")

testing if vector is converted successfully
mytraspose successfully transpose 
[1, 2, 3, 4]
into
[1, 2, 3, 4]

mytraspose successfully transpose 
['this', 'is', 'a', 'apple']
into
['this', 'is', 'a', 'apple']

mytraspose successfully transpose 
[1 2 3 4]
into
[1 2 3 4]

mytraspose successfully transpose 
[True, True, False, False]
into
[True, True, False, False]

function mytranspose can transpose vector


In [13]:
# dataset matrix
matrix_1 = [[1,2],[3,4]] #2d list
matrix_2 = [[],[],[]]
matrix_3 = np.array([[1,2],[3,4],[5,6]])
matrix_4 = pd.DataFrame(data=[[1,2,3],[4,5,6]])

In [14]:
# testing 2d
# testing vector case
print("testing if matrix is converted successfully")
successed_all = True
for x in [matrix_1, matrix_2, matrix_3, matrix_4]:
    successed = test_mytranspose(x)
successed_all = successed_all & successed
if successed_all:
    print("function mytranspose can transpose matrix")

testing if matrix is converted successfully
mytraspose successfully transpose 
[[1, 2], [3, 4]]
into
[[1, 3], [2, 4]]

falied to transpose
[[], [], []]
[]
should have been obtained. but
[[], [], []]
was obtained

mytraspose successfully transpose 
[[1 2]
 [3 4]
 [5 6]]
into
[[1, 3, 5], [2, 4, 6]]

falied to transpose
   0  1  2
0  1  2  3
1  4  5  6
   0  1
0  1  4
1  2  5
2  3  6
should have been obtained. but
[[1, 2], [4, 5]]
was obtained



/tmp/ipykernel_4481/1591580117.py:5: DeprecationWarning: elementwise comparison failed; this will raise an error in the future.
  same = (x==y)
