In [1]:
from mytranspose import *

In [2]:
# dimension testing

In [3]:
def dimtest(x, true_dim)->bool:
    my_dim = dim(x)
    success = (my_dim == true_dim)
    if success:
        print(x)
        print("has dimension")
        print(true_dim)
        print("succeed dimtest")
    else:
        print(x)
        print("has dimension")
        print(true_dim, " but we got ", my_dim)
    return success

In [4]:
dimtest_example_none, truedim_none = None, []
dimtest_example_0d, truedim_0d = "This is a scalar", []
dimtest_example_1d, truedim_1d = ["This","is", "a", "vector"], [4]
dimtest_example_2d, truedim_2d =[["This","is"], ["a", "matrix"],["of","strings"]], [3,2]
dimtest_example_3d, truedim_3d = [[["This","is"], ["a", "hypermatrix"],["of","strings"]], [["which","has"], ["shape", "2"],["3","2"]]], [2,3,2]

In [5]:
succeed_all = True
for x, truedim in zip([dimtest_example_none, dimtest_example_0d, dimtest_example_1d, dimtest_example_2d, dimtest_example_3d],[truedim_none, truedim_0d, truedim_1d, truedim_2d, truedim_3d]):

    succeed_all = succeed_all & dimtest(x, truedim)
if succeed_all:
    print("dimtest succeed")

None
has dimension
[]
succeed dimtest
This is a scalar
has dimension
[]
succeed dimtest
['This', 'is', 'a', 'vector']
has dimension
[4]
succeed dimtest
[['This', 'is'], ['a', 'matrix'], ['of', 'strings']]
has dimension
[3, 2]
succeed dimtest
[[['This', 'is'], ['a', 'hypermatrix'], ['of', 'strings']], [['which', 'has'], ['shape', '2'], ['3', '2']]]
has dimension
[2, 3, 2]
succeed dimtest
dimtest succeed


In [6]:
# rectangular testing

In [7]:
def rectangular_test(x, true_rectangular:bool)->bool:
    my_rectangular = is_rectangular(x)
    success = (my_rectangular == true_rectangular)
    if success:
        print(x)
        if true_rectangular:
            print("is rectangular")
        else:
            print("is not rectangular")
        print("succeed rectangular test")
    else:
        print(x)
        if true_rectangular:
            print("is rectangular. But we got result that x is not rectangular")
        else:
            print("is not rectangular. But we got result that x is rectangular")
    return success

In [8]:
rectest_example_true_none, rectest_label_none = None, True # []
rectest_example_true_0d, rectest_label_true_0d = 1234, True # []
rectest_example_true_1d, rectest_label_true_1d = [1,2,3,4], True # [4]
rectest_example_true_2d, rectest_label_true_2d = [[1,2,3],[4,5,6]], True # [2,3]
rectest_example_false_2d, rectest_label_false_2d = [[1,2],[3,4,5]], False # [2,?]
rectest_example_true_3d, rectest_label_true_3d = [[[1,2,3],[4,5,6],[7,8,9]],[[1,2],[3,4],[5,6]]], True # [2,3,?]
rectest_example_false_3d, rectest_label_false_3d = [[[1,2,3],[4,5,6],[7,8,9]],[[1,2,3],[4,5,6]]], False # [2,?,3]

In [9]:
succeed_all = True
for x, true_rectangular in zip([rectest_example_true_none,rectest_example_true_0d,rectest_example_true_1d,rectest_example_true_2d,rectest_example_true_3d,rectest_example_false_2d,rectest_example_false_3d],
        [rectest_label_none,rectest_label_true_0d,rectest_label_true_1d,rectest_label_true_2d,rectest_label_true_3d,rectest_label_false_2d,rectest_label_false_3d]):
    succeed_all = succeed_all & rectangular_test(x, true_rectangular)
if succeed_all:
    print("rectangular_test succeed")

None
is rectangular
succeed rectangular test
1234
is rectangular
succeed rectangular test
[1, 2, 3, 4]
is rectangular
succeed rectangular test
[[1, 2, 3], [4, 5, 6]]
is rectangular
succeed rectangular test
[[[1, 2, 3], [4, 5, 6], [7, 8, 9]], [[1, 2], [3, 4], [5, 6]]]
is rectangular
succeed rectangular test
[[1, 2], [3, 4, 5]]
is not rectangular
succeed rectangular test
[[[1, 2, 3], [4, 5, 6], [7, 8, 9]], [[1, 2, 3], [4, 5, 6]]]
is not rectangular
succeed rectangular test
rectangular_test succeed


In [10]:
#my_transpose testing

In [11]:
def test_mytranspose(x, true_tp)->bool:
    my_tp = mytranspose(x)
    success = (my_tp==true_tp)
    if success:
        print("mytranspose successfully transposed")
        print(x)
        print("to")
        print(my_tp)
    else:
        print("mytranspose failied to transpose")
        print(x)
        print("to")
        print(true_tp)
        print("instead")
        print(my_tp)
        print("was obtained")
    return success

In [12]:
# null testing

In [13]:
null_dataset_1, null_transpose_1 = None, None

In [14]:
succeed_all = True
for x, true_tp in zip([null_dataset_1],[null_transpose_1]):
    succeed_all = succeed_all & test_mytranspose(x, true_tp)
if succeed_all:
    print("null transposing succeed")

mytranspose successfully transposed
None
to
None
null transposing succeed


In [15]:
# scalar testing

In [16]:
scalar_dataset_1, scalar_transpose_1 = "string scalar", "string scalar"
scalar_dataset_2, scalar_transpose_2 = 1234, 1234

In [17]:
succeed_all = True
for x, true_tp in zip([scalar_dataset_1,scalar_dataset_2],[scalar_transpose_1,scalar_transpose_2]):
    succeed_all = succeed_all & test_mytranspose(x,true_tp)
if succeed_all:
    print("scalar transposing succeed")

mytranspose successfully transposed
string scalar
to
string scalar
mytranspose successfully transposed
1234
to
1234
scalar transposing succeed


In [18]:
# vector testing

In [19]:
vector_dataset_1, vector_transpose_1 = ["string","vector"], ["string","vector"]
vector_dataset_2, vector_transpose_2 = [1,2,3,4], [1,2,3,4]
vector_dataset_3, vector_transpose_3 = ["mixed", "vector", 1, 2], ["mixed", "vector", 1, 2]

In [20]:
succeed_all = True
for x, true_tp in zip([vector_dataset_1,vector_dataset_2,vector_dataset_3],[vector_transpose_1,vector_transpose_2,vector_transpose_3]):
    succeed_all = succeed_all & test_mytranspose(x, true_tp)
if succeed_all:
    print("vector transposing succeed")

mytranspose successfully transposed
['string', 'vector']
to
['string', 'vector']
mytranspose successfully transposed
[1, 2, 3, 4]
to
[1, 2, 3, 4]
mytranspose successfully transposed
['mixed', 'vector', 1, 2]
to
['mixed', 'vector', 1, 2]
vector transposing succeed


In [21]:
# matraix testing

In [22]:
matrix_dataset_1, matrix_transpose_1 = [["string", "matrix"],["my","transpose"]], [["string","my"],["matrix","transpose"]]
matrix_dataset_2, matrix_transpose_2 = [[1,2,3],[4,5,6]], [[1,4],[2,5],[3,6]]
matrix_dataset_3, matrix_transpose_3 = [["scalar","matrix",1,2],["numeric","matrix",1,2]], [["scalar","numeric"],["matrix","matrix"],[1,1],[2,2]]

In [23]:
succeed_all = True
for x, true_tp in zip([matrix_dataset_1,matrix_dataset_2,matrix_dataset_3],[matrix_transpose_1,matrix_transpose_2,matrix_transpose_3]):
    succeed_all = succeed_all & test_mytranspose(x, true_tp)
if succeed_all:
    print("matrix transposing succeed")

mytranspose successfully transposed
[['string', 'matrix'], ['my', 'transpose']]
to
[['string', 'my'], ['matrix', 'transpose']]
mytranspose successfully transposed
[[1, 2, 3], [4, 5, 6]]
to
[[1, 4], [2, 5], [3, 6]]
mytranspose successfully transposed
[['scalar', 'matrix', 1, 2], ['numeric', 'matrix', 1, 2]]
to
[['scalar', 'numeric'], ['matrix', 'matrix'], [1, 1], [2, 2]]
matrix transposing succeed


In [24]:
# hypermatrix testing

In [25]:
hypermatrix_dataset_1, hypermatrix_transpose_1 = [[[1,2],[3,4]],[[5,6],[7,8]]], [[[1,2],[5,6]],[[3,4],[7,8]]]
hypermatrix_dataset_2, hypermatrix_transpose_2 = [[["string","hyper"],["matrix","transpose"]],[["testing","should"],["be","successful"]]],[[["string","hyper"],["testing","should"]],[["matrix","transpose"],["be","successful"]]]
hypermatrix_dataset_3, hypermatrix_transpose_3 = [[[1,2],[3,4],[5,6]],[[7],[8],[9]]], [[[1,2],[7]],[[3,4],[8]],[[5,6],[9]]]

In [26]:
succeed_all = True
for x, true_tp in zip([hypermatrix_dataset_1,hypermatrix_dataset_2,hypermatrix_dataset_3],[hypermatrix_transpose_1,hypermatrix_transpose_2,hypermatrix_transpose_3]):
    succeed_all = succeed_all & test_mytranspose(x,true_tp)
if succeed_all:
    print("hypermatrix transposing succeed")

mytranspose successfully transposed
[[[1, 2], [3, 4]], [[5, 6], [7, 8]]]
to
[[[1, 2], [5, 6]], [[3, 4], [7, 8]]]
mytranspose successfully transposed
[[['string', 'hyper'], ['matrix', 'transpose']], [['testing', 'should'], ['be', 'successful']]]
to
[[['string', 'hyper'], ['testing', 'should']], [['matrix', 'transpose'], ['be', 'successful']]]
mytranspose successfully transposed
[[[1, 2], [3, 4], [5, 6]], [[7], [8], [9]]]
to
[[[1, 2], [7]], [[3, 4], [8]], [[5, 6], [9]]]
hypermatrix transposing succeed


In [27]:
# Additional Work
# Numpy implement of testmytranspose

In [28]:
import numpy as np

In [29]:
# dim test

In [30]:
np_dimtest_example_none, np_truedim_none = np.nan, []
np_dimtest_example_0d, np_truedim_0d = np.complex(1,2), []
np_dimtest_example_1d, np_truedim_1d = np.array([1,2,3,4]), [4]
np_dimtest_example_2d, np_truedim_2d = np.array([[1,2,3],[4,5,6]]), [2,3]
np_dimtest_example_3d, np_truedim_3d = np.array([[[1,2,3],[4,5,6]],[[7,8,9],[10,11,12]]]), [2,2,3]

/tmp/ipykernel_8866/179530117.py:2: DeprecationWarning: `np.complex` is a deprecated alias for the builtin `complex`. To silence this warning, use `complex` by itself. Doing this will not modify any behavior and is safe. If you specifically wanted the numpy scalar type, use `np.complex128` here.
Deprecated in NumPy 1.20; for more details and guidance: https://numpy.org/devdocs/release/1.20.0-notes.html#deprecations
  np_dimtest_example_0d, np_truedim_0d = np.complex(1,2), []


In [31]:
succeed_all = True
for x, truedim in zip([np_dimtest_example_none, np_dimtest_example_0d, np_dimtest_example_1d, np_dimtest_example_2d, np_dimtest_example_3d],[np_truedim_none, np_truedim_0d, np_truedim_1d, np_truedim_2d, np_truedim_3d]):
    succeed_all = succeed_all & dimtest(x, truedim)
if succeed_all:
    print("dimtest succeed")

nan
has dimension
[]
succeed dimtest
(1+2j)
has dimension
[]
succeed dimtest
[1 2 3 4]
has dimension
[4]
succeed dimtest
[[1 2 3]
 [4 5 6]]
has dimension
[2, 3]
succeed dimtest
[[[ 1  2  3]
  [ 4  5  6]]

 [[ 7  8  9]
  [10 11 12]]]
has dimension
[2, 2, 3]
succeed dimtest
dimtest succeed


In [32]:
# rectangular test
# array is forced to be rectangular so no rectangular test needed

In [33]:
# my transpose testing

In [34]:
def np_test_mytranspose(x, true_tp)->bool:
    my_tp = mytranspose(x)
    success = np.array((my_tp==true_tp)|((my_tp != my_tp)&(true_tp != true_tp))).all() # identical or nan in both
    if success:
        print("mytranspose successfully transposed")
        print(x)
        print("to")
        print(my_tp)
    else:
        print("mytranspose failied to transpose")
        print(x)
        print("to")
        print(true_tp)
        print("instead")
        print(my_tp)
        print("was obtained")
    return success

In [35]:
# none testing

In [36]:
np_none_dataset_1, np_none_transpose_1 = np.nan, np.nan
np_none_dataset_2, np_none_transpose_2 = np.inf, np.inf

In [37]:
succeed_all = True
for x, true_tp in zip([np_none_dataset_1,np_none_dataset_2],[np_none_transpose_1,np_none_transpose_2]):
    succeed_all = succeed_all & np_test_mytranspose(x, true_tp)
if succeed_all:
    print("mytranspose can transpose np none")

mytranspose successfully transposed
nan
to
nan
mytranspose successfully transposed
inf
to
inf
mytranspose can transpose np none


In [38]:
# scalar testing

In [39]:
np_scalar_dataset_1, np_scalar_transpose_1 = np.complex(1,2), np.complex(1,2)
np_scalar_dataset_2, np_scalar_transpose_2 = np.float64(1.23456), np.float(1.23456)

/tmp/ipykernel_8866/1481855360.py:1: DeprecationWarning: `np.complex` is a deprecated alias for the builtin `complex`. To silence this warning, use `complex` by itself. Doing this will not modify any behavior and is safe. If you specifically wanted the numpy scalar type, use `np.complex128` here.
Deprecated in NumPy 1.20; for more details and guidance: https://numpy.org/devdocs/release/1.20.0-notes.html#deprecations
  np_scalar_dataset_1, np_scalar_transpose_1 = np.complex(1,2), np.complex(1,2)
/tmp/ipykernel_8866/1481855360.py:2: DeprecationWarning: `np.float` is a deprecated alias for the builtin `float`. To silence this warning, use `float` by itself. Doing this will not modify any behavior and is safe. If you specifically wanted the numpy scalar type, use `np.float64` here.
Deprecated in NumPy 1.20; for more details and guidance: https://numpy.org/devdocs/release/1.20.0-notes.html#deprecations
  np_scalar_dataset_2, np_scalar_transpose_2 = np.float64(1.23456), np.float(1.23456)


In [40]:
succeed_all = True
for x, true_tp in zip([np_scalar_dataset_1,np_scalar_dataset_2],[np_scalar_transpose_1,np_scalar_transpose_2]):
    succeed_all = succeed_all & np_test_mytranspose(x, true_tp)
if succeed_all:
    print("mytranspose can transpose np scalar")

mytranspose successfully transposed
(1+2j)
to
(1+2j)
mytranspose successfully transposed
1.23456
to
1.23456
mytranspose can transpose np scalar


In [41]:
# vector testing

In [42]:
np_vector_dataset_1, np_vector_transpose_1 = np.array(["String","Vector"]), np.array(["String","Vector"])
np_vector_dataset_2, np_vector_transpose_2 = np.array([1,2,3,4]), np.array([1,2,3,4])
np_vector_dataset_3, np_vector_transpose_3 = np.array([True,True,False,True]), np.array([True,True,False,True])
np_vector_dataset_4, np_vector_transpose_4 = np.array(["Mixed","Vector",1,None,True]), np.array(["Mixed","Vector",1,None,True])

In [43]:
succeed_all = True
for x, true_tp in zip([np_vector_dataset_1,np_vector_dataset_2,np_vector_dataset_3,np_vector_dataset_4],
                      [np_vector_transpose_1,np_vector_transpose_2,np_vector_transpose_3,np_vector_transpose_4]):
    succeed_all = succeed_all & np_test_mytranspose(x, true_tp)
if succeed_all:
    print("mytranspose can transpose np vector")

mytranspose successfully transposed
['String' 'Vector']
to
['String' 'Vector']
mytranspose successfully transposed
[1 2 3 4]
to
[1 2 3 4]
mytranspose successfully transposed
[ True  True False  True]
to
[ True  True False  True]
mytranspose successfully transposed
['Mixed' 'Vector' 1 None True]
to
['Mixed' 'Vector' 1 None True]
mytranspose can transpose np vector


In [44]:
# matrix testing

In [45]:
np_matrix_dataset_1, np_matrix_transpose_1 = np.array([["This","is"],["string","vector"]]), np.array([["This","string"],["is","vector"]])
np_matrix_dataset_2, np_matrix_transpose_2 = np.array([[1,2],[np.nan, np.inf]]), np.array([[1,np.nan],[2,np.inf]])
np_matrix_dataset_3, np_matrix_transpose_3 = np.array([[True,True,False],[False,False,False]]), np.array([[True,False],[True,False],[False,False]])
np_matrix_dataset_4, np_matrix_transpose_4 = np.array([[1,2],[3,4],[5,6],[7,8]]), np.array([[1,3,5,7],[2,4,6,8]])

In [46]:
succeed_all = True
for x, true_tp in zip([np_matrix_dataset_1,np_matrix_dataset_2,np_matrix_dataset_3,np_matrix_dataset_4],
                      [np_matrix_transpose_1,np_matrix_transpose_2,np_matrix_transpose_3,np_matrix_transpose_4]):
    succeed_all = succeed_all & np_test_mytranspose(x,true_tp)
if succeed_all:
    print("mytranspose can transpose np matrix")

mytranspose successfully transposed
[['This' 'is']
 ['string' 'vector']]
to
[['This' 'string']
 ['is' 'vector']]
mytranspose successfully transposed
[[ 1.  2.]
 [nan inf]]
to
[[ 1. nan]
 [ 2. inf]]
mytranspose successfully transposed
[[ True  True False]
 [False False False]]
to
[[ True False]
 [ True False]
 [False False]]
mytranspose successfully transposed
[[1 2]
 [3 4]
 [5 6]
 [7 8]]
to
[[1 3 5 7]
 [2 4 6 8]]
mytranspose can transpose np matrix


In [47]:
# hypermatrix testing

In [48]:
np_hypermatrix_dataset_1, np_hypermatrix_transpose_1 = np.array([[[True,True],[True,False],[False,False]],[[False,False],[False,True],[True,True]]]), np.array([[[True,True],[False,False]],[[True,False],[False,True]],[[False,False],[True,True]]])
np_hypermatrix_dataset_2, np_hypermatrix_transpose_2 = np.array([[[np.nan,np.nan],[np.inf,np.inf]],[[None,None],[0,0]]]),np.array([[[np.nan,np.nan],[None,None]],[[np.inf,np.inf],[0,0]]])
np_hypermatrix_dataset_3, np_hypermatrix_transpose_3 = np.array([[["s","st"],["str","stri"]],[["strin","string"],["n","nu"]],[["num","numb"],["numbe","number"]]]), np.array([[["s","st"],["strin","string"],["num","numb"]],[["str","stri"],["n","nu"],["numbe","number"]]])
np_hypermatrix_dataset_4, np_hypermatrix_transpose_4 = np.array([[[1,2,3],[10,20,30]],[[100,200,300],[1000,2000,3000]]]), np.array([[[1,2,3],[100,200,300]],[[10,20,30],[1000,2000,3000]]])

In [49]:
succeed_all = True
for x, true_tp in zip([np_hypermatrix_dataset_1,np_hypermatrix_dataset_2,np_hypermatrix_dataset_3,np_hypermatrix_dataset_4],
                      [np_hypermatrix_transpose_1,np_hypermatrix_transpose_2,np_hypermatrix_transpose_3,np_hypermatrix_transpose_4]):
    succeed_all = succeed_all & np_test_mytranspose(x,true_tp)
if succeed_all:
    print("mytranspose can transpose np hypermatrix")

mytranspose successfully transposed
[[[ True  True]
  [ True False]
  [False False]]

 [[False False]
  [False  True]
  [ True  True]]]
to
[[[ True  True]
  [False False]]

 [[ True False]
  [False  True]]

 [[False False]
  [ True  True]]]
mytranspose successfully transposed
[[[nan nan]
  [inf inf]]

 [[None None]
  [0 0]]]
to
[[[nan nan]
  [None None]]

 [[inf inf]
  [0 0]]]
mytranspose successfully transposed
[[['s' 'st']
  ['str' 'stri']]

 [['strin' 'string']
  ['n' 'nu']]

 [['num' 'numb']
  ['numbe' 'number']]]
to
[[['s' 'st']
  ['strin' 'string']
  ['num' 'numb']]

 [['str' 'stri']
  ['n' 'nu']
  ['numbe' 'number']]]
mytranspose successfully transposed
[[[   1    2    3]
  [  10   20   30]]

 [[ 100  200  300]
  [1000 2000 3000]]]
to
[[[   1    2    3]
  [ 100  200  300]]

 [[  10   20   30]
  [1000 2000 3000]]]
mytranspose can transpose np hypermatrix
